# -*- coding: utf-8 -*-
"""Analise_Exploratoria_de_Dados_Parte_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZYU9T1bgo-tBQBY9vF3xIJ3j4WsCUcM

**Grupo:**

Ana Beatriz Soares

Danielle Stephany

Michelly Darquia

Gabriel Alves

Gabriel Agra

---

Tópicos adicionados para a parte 2:

- 3.5
- 6
- 7

# 1 - Introdução e Entendimento Inicial

### 1.1 - Objetivo da análise

Esta análise visa identificar padrões e variáveis determinantes para o desenvolvimento de quadros depressivos em estudantes, fornecendo suporte para a construção de um modelo de classificação binária (0: sem depressão, 1: com depressão).

## 1.2 - Contexto do dataset

O dataset utilizado nesse projeto contém informações relacionadas a depressão em estudantes. A partir desses dados, pretende-se analisar padrões e características que possam contribuir para o desenvolvimento de um modelo de Machine Learning que deve responder a seguinte pergunta: Quais fatores aumentam a chance de depressão em estudantes?

**Tema do dataset:** Student Depression Dataset

**Fonte dos dados:** Kaggle

## 1.3 - Entendimento Inicial dos Dados

Nesta etapa, foram importadas as bibliotecas necessárias, realizado o carregamento do dataset e visualizadas as primeiras linhas dos dados, com o objetivo de verificar se a importação ocorreu corretamente e sem problemas de formatação.
- O dataset possui **27.901** registros e **18** variáveis, sendo **17 features** e **1 variável alvo** (Depression).
- O problema é de Classificação Binária Supervisionada, onde:

    0 = Sem depressão

    1 = Com depressão
- A variável alvo apresenta uma distribuição relativamente equilibrada:

    58,5% dos estudantes possuem depressão;
    
    41,5% não possuem depressão.
- A idade dos participantes varia entre 18 e 59 anos, com média de aproximadamente **25,8 anos**.
- O desempenho acadêmico (CGPA) apresenta **média de 7,66**.
- A coluna id possui valores únicos para todos os registros.
- Algumas variáveis apresentam **baixa variabilidade**, como Work Pressure e Job Satisfaction.
"""

# importação das bibliotecas

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

#pip install missingno
import missingno as msno

# Install dependencies as needed:
#pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Student Depression Dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "hopesb/student-depression-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

# visualização inicial dos dados

print('HEAD\n')
print(df.head())

print('\n\nTAIL\n')
print(df.tail())

print('\n\nSAMPLE\n')
df.sample(5)

# tamanho do dataset

print(f'tamanho: {df.shape}')
print(f'o dataset possui {df.shape[0]} linhas e {df.shape[1]} colunas')

# informações gerais

print('\nnome das colunas:')
list(df.columns)

# tipos dos dados
print('\ntipos dos dados:')
print(df.dtypes)

# valores unicos por coluna

print('valores unicos por coluna:')
print(df.nunique().sort_values())

# verificação da variavel alvo

target = "Depression"

X = df.drop(columns=[target])
y = df[target]

print(f"variável alvo: {target}")
print(f"número de features: {X.shape[1]}")

print('\n\nHEAD\n')
print(df[target].head())

print('\n\nTAIL\n')
print(df[target].tail())

# como problema classificação

print(f'\n\n{df[target].value_counts(normalize=True) * 100}')

"""## 1.4 - Classificação das variáveis

Ao analisar a saída referente à coluna do dataset, as variáveis foram classificadas em númericas, categóricas, identificadoras e variável alvo. Não foram identificadas variáveis temporais, uma vez que o conjunto de dados não possui colunas relacionadas a datas ou horários. Também não foram encontradas variáveis textuais livres, sendo todas as variáveis categóricas compostas por categorias pré-definidas.
"""

# separação inicial por tipo de variável

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object', 'category']).columns

"""### 1.4.1 - Variáveis numéricas"""

print('variáveis numéricas:')
print(list(num_cols))

# resumo estatistico das variáveis numéricas

print('resumo')
print(df.describe())

# variaveis numericas contínuas
num_continuas = [
    'Age',
    'CGPA',
    'Work/Study Hours'
]

# variáveis numéricas ordinais
num_ordinais = [
    'Academic Pressure',
    'Work Pressure',
    'Study Satisfaction',
    'Job Satisfaction',
    'Financial Stress'
]

print('variaveis numericas continuas\n:')
print(df[num_continuas].describe())
for col in num_ordinais:
    print(f"\n{col}")
    print(sorted(df[col].unique()))

print('\n\nvariaveis numericas ordinais\n:')
print(df[num_ordinais].describe())

"""### 1.4.2 - Variáveis categóricas"""

print('variáveis categóricas:')
print(list(cat_cols))

# resumo estatistico das variáveis categóricas

print('resumo')
print(df.describe(include='object'))

"""### 1.4.3 - Variáveis identificadoras"""

# variavel identificadora

print(df['id'].describe())
print(f"quantidade de registros: {len(df)}")
print(f"IDs únicos: {df['id'].nunique()}")
print(f"possui IDs repetidos? {df['id'].nunique() != len(df)}")

"""## 1.5 - Tabela Resumo"""

# tabela resumo

resumo_variaveis = pd.DataFrame({
    "variavel": df.columns,
    "tipo_pandas": df.dtypes.astype(str).values,
    "valores_unicos": df.nunique().values,
    "percentual_unicos": (df.nunique().values / len(df) * 100).round(2),
    "missing": df.isnull().sum().values,
    "missing_percent": (df.isnull().mean().values * 100).round(2)
})

print(resumo_variaveis)

"""## 2. Qualidade e Tratamento de Dados

Esta etapa focou na integridade do *dataset*, visando mitigar ruídos que comprometam a performance do modelo preditivo. O processo foi estruturado em três eixos:

1. **Identificação de *Missing Values*:** Mapeamento de lacunas para definição de políticas de imputação ou descarte.
2. **Detecção de Duplicatas:** Eliminação de registros redundantes para evitar o enviesamento do treinamento.
3. **Validação de Consistência Lógica:** Verificação de *outliers* estruturais, como faixas etárias fora do espectro acadêmico ou valores de CGPA fora da escala nominal.

A integridade do dataset apresenta alta qualidade, com volume de dados faltantes estatisticamente irrelevante.

  - Magnitude: Foram identificados apenas 3 valores nulos em um conjunto de 27.901 registros, correspondendo a aproximadamente 0,01% do total.

  - Distribuição: A ausência é restrita à variável Financial Stress (IDs 68910, 97610 e 22377). As demais 16 variáveis encontram-se 100% preenchidas.

  - Diagnóstico: A natureza pontual e isolada das falhas indica erros aleatórios de coleta (Missing Completely at Random - MCAR), descartando comprometimento estrutural do sistema de aquisição.
"""

# valores ausentes

print(df.isnull().sum())

print('\n\npercentual de valores ausentes:')
print((df.isnull().mean() * 100).sort_values(ascending=False))

# tabela resumo

missing_values = pd.DataFrame({
    "variavel": df.columns,
    "missing_count": df.isnull().sum().values,
    "missing_percent": (df.isnull().mean().values * 100).round(2)
})

missing_values = missing_values.sort_values(
    by="missing_percent",
    ascending=False
)

print(missing_values)

total_missing = df.isnull().sum().sum()

print(f"Total de valores ausentes no dataset: {total_missing}")

missing_values_plot = missing_values[missing_values["missing_count"] > 0]

plt.figure(figsize=(12, 6))
sns.barplot(
    data=missing_values_plot,
    x="missing_percent",
    y="variavel"
)
plt.title("Percentual de Valores Ausentes por Variável")
plt.xlabel("Percentual de valores ausentes (%)")
plt.ylabel("Variável")
plt.show()

# matriz de ausencia
msno.matrix(df)
plt.show()

# grafico de barras
msno.bar(df)
plt.show()

# mapa correlação entre ausnencias
msno.heatmap(df)
plt.show()

missing_por_linha = df.isnull().sum(axis=1)

print(missing_por_linha.describe())

print('\n')
print(df.loc[missing_por_linha.sort_values(ascending=False).head(10).index])

percent_missing_linha = df.isnull().mean(axis=1) * 100

print('\n')
print(percent_missing_linha.describe())

"""## 2.2 - Análise de duplicatas


"""

# Verificação real de alunos com respostas 100% idênticas
duplicatas_reais = df.drop(columns=['id']).duplicated().sum() # IGNORA O ID POIS ELE SEMPRE FORÇA A LINHA A SER DIFERENTE DA OUTRA
print(f"Alunos com perfis exatamente iguais: {duplicatas_reais}")

"""## 2.3 - Análise de Inconsistências

Após a verificação dos limites lógicos e da cardinalidade das variáveis categóricas, foi constatado que o dataset necessita de limpeza em colunas específicas:

* **Problema na Coluna "City":** Esta variável contém inconsistência na coleta de dados. Identificamos:
    * **Entradas sem sentido ou valores de outras colunas misturados**
    * **Erros de digitação**
    * **Entradas que parecem nomes de pessoas em vez de cidades**
    
* **Forte Desbalanceamento em "Profession":** O dataset é massivamente composto por Estudantes (27.870 casos), enquanto outras 13 profissões (como Arquiteto, Professor, Chef) somam apenas 31 casos no total. Dado o nome e objetivo do dataset, a presença de não-estudantes é um **ruído**. A estratégia ideal será filtrar o dataframe para manter `Profession == 'Student'` e, em seguida, remover a coluna, pois ela passará a ter apenas um valor único e não ajudará o modelo.
"""

# valores unicos por coluna

for col in df.columns:
    print(f"\nColuna: {col}")
    print(f"Tipo: {df[col].dtype}")
    print(f"Valores únicos: {df[col].nunique()}")
    print(df[col].dropna().unique()[:20])
    print("-" * 50)

# colunas com alta cardinalidade

cardinalidade = pd.DataFrame({
    "variavel": df.columns,
    "valores_unicos": df.nunique().values,
    "percentual_unicos": (df.nunique().values / len(df) * 100).round(2)
}).sort_values(by="percentual_unicos", ascending=False)

print(cardinalidade)

print('\n')
alta_cardinalidade = cardinalidade[cardinalidade["percentual_unicos"] > 50]

print(alta_cardinalidade)

"""### 2.3.1 - Valores impossíveis"""

print(df[(df['Age'] < 0) | (df['Age'] > 100)])

print('\n')
print(df[(df['CGPA'] < 0) | (df['CGPA'] > 10)])

print('\n')
print(df[
    ~df['Academic Pressure'].isin([1,2,3,4,5])
])

print('\n')
print(sorted(df['Study Satisfaction'].dropna().unique()))

print('\n')
print(sorted(df['Job Satisfaction'].dropna().unique()))

print('\n')
print(sorted(df['Financial Stress'].dropna().unique()))

print('\n')
print(df[(df['Work/Study Hours'] < 0)])

print('\n')
print(df[(df['Work/Study Hours'] > 24)])

print('\n')
print(df['Gender'].value_counts(dropna=False))

print('\n')
print(df['Depression'].value_counts(dropna=False))

print('\n')
print(df['Have you ever had suicidal thoughts ?'].value_counts(dropna=False))

print('\n')
print(df['Family History of Mental Illness'].value_counts(dropna=False))

"""### 2.3.2 - Erros de digitação"""

cat_cols = [
    'Gender',
    'City',
    'Profession',
    'Sleep Duration',
    'Dietary Habits',
    'Degree',
    'Have you ever had suicidal thoughts ?',
    'Family History of Mental Illness',
    'Depression'
]

for col in cat_cols:
    print(f"\n{'='*50}")
    print(col)
    print(df[col].unique())

"""### 2.3.3 - Categorias repetidas"""

for col in cat_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

"""# 3 - Exploração de Dados (EDA)

Nesta fase central do projeto, foi explorado o comportamento das variáveis para descobrir os padrões ocultos nos dados. Para manter a clareza, estruturamos essa exploração em quatro etapas lógicas:

1. **Visão Individual (Univariada e Distribuições):** Analisar o comportamento isolado de cada característica, mapeando como os dados estão distribuídos e suas frequências.
2. **Visão Cruzada (Bivariada):** Relacionar as variáveis do dataset com o nosso alvo e entre si, permitindo validar hipóteses de negócio.
3. **Visão Global (Multivariada e Correlações):** Mapear as relações matemáticas de todo o conjunto e checar possíveis vazamentos de dados (data leakage).

## 3.1 Visão Individual (Análise Univariada)

### 3.1.1 - Variáveis Numéricas
"""

cols_to_plot = ['Age', 'CGPA', 'Work/Study Hours', 'Academic Pressure']

plt.figure(figsize=(15, 10))
for i, col in enumerate(cols_to_plot, 1):
    plt.subplot(2, 2, i)
    sns.histplot(df[col], kde=True, color='skyblue')
    plt.title(f'Distribuição de {col}')
plt.tight_layout()
plt.show()

for col in num_continuas:
    plt.figure(figsize=(6,2))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot - {col}')
    plt.show()

num_ordinais = [
    'Academic Pressure',
    'Work Pressure',
    'Study Satisfaction',
    'Job Satisfaction',
    'Financial Stress'
]

print(df[num_ordinais].describe())

print('\n')
for col in num_ordinais:
    print(f"\n{col}")
    print(df[col].value_counts().sort_index())

for col in num_ordinais:
    plt.figure(figsize=(6,4))

    sns.countplot(
        data=df,
        x=col,
        order=sorted(df[col].dropna().unique())
    )

    plt.title(col)
    plt.show()

"""### 3.1.2 - Variáveis categóricas"""

cat_cols = [
    'Gender',
    'City',
    'Profession',
    'Sleep Duration',
    'Dietary Habits',
    'Degree',
    'Have you ever had suicidal thoughts ?',
    'Family History of Mental Illness'
]

# frequencia absoluta
for col in cat_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

print('\n')
# frequencia relativa
for col in cat_cols:
    print(f"\n{col}")
    print(
        round(
            df[col].value_counts(normalize=True) * 100,
            2
        )
    )

for col in cat_cols:

    plt.figure(figsize=(8,4))

    sns.countplot(
        data=df,
        x=col,
        order=df[col].value_counts().index
    )

    plt.xticks(rotation=45)
    plt.title(col)
    plt.show()

plt.figure(figsize=(10,5))

df['City'].value_counts().head(10).plot(kind='bar')

plt.title('Top 10 cidades')
plt.show()

"""### 3.1.3 - Variável alvo"""

target = 'Depression'

print(df[target].value_counts())

print('\n')

print(round(df[target].value_counts(normalize=True) * 100, 2))

plt.figure(figsize=(6,4))

sns.countplot(
    data=df,
    x=target
)

plt.title('Distribuição da Variável Alvo')
plt.show()

"""## 3.2 Visão Cruzada (Análise Bivariada)

Nesta etapa, as variáveis do dataset foram cruzadas para entender como elas interagem entre si e como elas afetam a nossa variável preditiva (`Depression`). A análise será dividida em quatro frentes:
1. **Numérica x Numérica:** Buscando correlações lineares ou agrupamentos.
2. **Numérica x Categórica:** Avaliando como as distribuições numéricas mudam dentro de cada grupo.
3. **Categórica x Categórica:** Verificando a frequência conjunta de categorias.
4. **Variáveis x Target:** O passo importante para identificar quais features têm maior peso indicativo sobre a depressão dos estudantes.

### 3.2.1 - Numérica x numérica
"""

print("Cruzamento: Numérica x Numérica")
num_cols_principais = ['Age', 'CGPA', 'Work/Study Hours', 'Academic Pressure']

# O pairplot gera gráficos de dispersão (scatterplots) combinando todas as numéricas
sns.pairplot(df[num_cols_principais], corner=True, plot_kws={'alpha':0.5})
plt.suptitle('Relação entre as Variáveis Numéricas', y=1.02)
plt.show()

"""### 3.2.2 - Numérica x categórica"""

# 9.2 Numérica x Categórica
print("Cruzamento: Numérica x Categórica")

plt.figure(figsize=(15, 6))

plt.subplot(1, 2, 1)
sns.boxplot(data=df, x='Sleep Duration', y='CGPA', palette='Set2')
plt.title('CGPA por Duração do Sono')
plt.xticks(rotation=45)

plt.subplot(1, 2, 2)
sns.boxplot(data=df, x='Sleep Duration', y='Work/Study Hours', palette='Set2')
plt.title('Horas de Trabalho/Estudo por Duração do Sono')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""### 3.2.3 - Categórica x categórica"""

print("Cruzamento: Categórica x Categórica")

crosstab_cat = pd.crosstab(df['Gender'], df['Dietary Habits'])

plt.figure(figsize=(8, 5))
sns.heatmap(crosstab_cat, annot=True, fmt='d', cmap='Blues')
plt.title('Gênero vs Hábitos Alimentares (Contagem)')
plt.show()

"""### 3.2.4 - Variáveis x target"""

print("Cruzamento: Variáveis x Target (Depressão)")

plt.figure(figsize=(16, 12))

# Numérica vs Target
plt.subplot(2, 2, 1)
sns.boxplot(data=df, x='Depression', y='Academic Pressure', palette='Set1')
plt.title('Pressão Acadêmica vs Depressão')

plt.subplot(2, 2, 2)
sns.boxplot(data=df, x='Depression', y='CGPA', palette='Set1')
plt.title('Notas (CGPA) vs Depressão')

# Categórica vs Target
plt.subplot(2, 2, 3)
sns.countplot(data=df, x='Sleep Duration', hue='Depression', palette='Set1')
plt.title('Duração do Sono vs Depressão')
plt.xticks(rotation=45)

plt.subplot(2, 2, 4)
sns.countplot(data=df, x='Financial Stress', hue='Depression', palette='Set1')
plt.title('Estresse Financeiro vs Depressão')

plt.tight_layout()
plt.show()

"""## 3.4 Visão Global (Correlações e Vazamento)"""

print("Mapa de Correlação (Pearson):\n")

cols_corr = ['Age', 'Academic Pressure', 'CGPA', 'Work/Study Hours', 'Financial Stress', 'Depression']
matriz_correlacao = df[cols_corr].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(matriz_correlacao, annot=True, fmt=".2f", cmap="coolwarm", vmin=-1, vmax=1, square=True)
plt.title('Correlação Matemática entre Variáveis Numéricas e o Target')
plt.show()

print("\nTop variáveis correlacionadas com a Depressão:")
print(matriz_correlacao['Depression'].sort_values(ascending=False))

"""### 3.4.2 - Variáveis Redundantes

Avaliando a matriz de correlação, foi observado o relacionamento entre as variáveis numéricas independentes:
* **Ausência de Redundância:** Como verificado nos cruzamentos das features, não há indícios de multicolinearidade. Nenhuma variável numérica apresenta correlação extrema entre si.
* **Conclusão:** Cada variável traz uma informação matemática única. Portanto, nenhuma coluna numérica precisará ser descartada por redundância.

### 3.4.3 - Vazamento de Dados (Data Leakage):

* **Análise Matemática:** A correlação máxima com a variável alvo (`Depression`) foi de **0.47** (Pressão Acadêmica). Por estar longe de 1.0, está totalmente descartada a hipótese de vazamento de dados direto nas variáveis numéricas.
* **Análise Lógica (Alerta Categórico):** Ressaltamos que a variável categórica `Have you ever had suicidal thoughts ?` requer atenção. Por ser um sintoma clínico direto da depressão, incluí-la no modelo pode causar target leakage. Isso torna o modelo capaz de "identificar" a depressão apenas pela presença do sintoma, e não pelos fatores de risco, o que compromete sua utilidade para um diagnóstico precoce.

### Principais Preditores Numéricos
Os fatores que mais pesam no diagnóstico neste dataset são:
1. **Pressão Acadêmica** (Correlação de **0.47**)
2. **Estresse Financeiro** (Correlação de **0.36**)
3. **Idade** (Correlação de **-0.23**): Mostra uma leve tendência inversa, indicando que estudantes mais jovens tendem a relatar mais os quadros de depressão.

As variáveis puramente de desempenho acadêmico, como as notas/CGPA (0.02), demonstraram impacto estatístico praticamente nulo no diagnóstico.

# 3.5 - Interpretações

## 3.5.1 - Interpretação da variável-alvo

A variável-alvo do projeto é **Depression**, que indica se o estudante apresenta ou não quadro de depressão. O problema é de **classificação binária supervisionada**, pois o objetivo é prever uma classe entre duas possibilidades:

- `0`: estudante sem depressão;
- `1`: estudante com depressão.

A variável-alvo não apresenta um desbalanceamento extremo. A classe `1` é mais frequente, com aproximadamente **58,5%** dos registros, enquanto a classe `0` representa cerca de **41,5%**. Isso indica um leve predomínio de estudantes com depressão, mas não um desequilíbrio tão severo a ponto de inviabilizar o treinamento dos modelos.

Mesmo assim, como a diferença entre as classes existe, será importante avaliar os modelos não apenas pela acurácia, mas também por métricas como **precision**, **recall**, **F1-score** e **matriz de confusão**. Para a divisão entre treino e teste, recomenda-se usar amostragem estratificada para preservar a proporção das classes.

## 3.5.2 - Interpretação das variáveis categóricas

As variáveis categóricas que parecem mais relevantes para o problema são:

- **Sleep Duration**, pois pode indicar relação entre sono e saúde mental;
- **Dietary Habits**, pois hábitos de alimentação podem estar associados ao bem-estar;
- **Have you ever had suicidal thoughts ?**, pois apresenta relação forte com depressão, mas também representa risco de **vazamento de dados**;
- **Family History of Mental Illness**, pois pode indicar histórico familiar associado à saúde mental;
- **Gender**, pois permite verificar possíveis diferenças entre grupos;
- **Degree**, pois pode representar diferenças entre áreas ou níveis de formação.

A coluna **City** apresenta alta cardinalidade e inconsistências, contendo valores que não parecem cidades válidas. Por isso, ela exige tratamento cuidadoso: pode ser removida, agrupada em categorias mais gerais ou codificada apenas se for considerada útil após limpeza.

A coluna **Profession** também exige atenção, pois o dataset é voltado para estudantes, mas contém poucos registros de outras profissões. A decisão adotada foi filtrar apenas `Profession == 'Student'` e depois remover a coluna, já que ela perde variabilidade.

Para modelagem, será necessário aplicar codificação nas variáveis categóricas. As variáveis binárias podem usar **Label Encoding**; variáveis ordinais, como qualidade da dieta e duração do sono, podem receber **Ordinal Encoding**; e variáveis nominais, como curso/grau, podem receber **One-Hot Encoding**.

## 3.5.3 - Interpretação das variáveis numéricas

As principais variáveis numéricas analisadas foram **Age**, **CGPA**, **Academic Pressure**, **Study Satisfaction**, **Work/Study Hours** e **Financial Stress**.

Algumas variáveis são contínuas, como `Age`, `CGPA` e `Work/Study Hours`. Outras são ordinais, como `Academic Pressure`, `Study Satisfaction` e `Financial Stress`, pois representam níveis ou escalas.

A análise indicou que:

- **Academic Pressure** e **Financial Stress** apresentam maior relação com a variável-alvo;
- **Age** apresenta uma relação negativa com a depressão, sugerindo maior incidência em estudantes mais jovens;
- **CGPA** não mostrou relação forte com a depressão;
- algumas variáveis podem apresentar valores extremos, mas nem todos devem ser tratados como erro, pois podem representar perfis reais de estudantes;
- como as variáveis estão em escalas diferentes, modelos sensíveis à escala, como KNN, SVM e Regressão Logística, devem usar **padronização** ou **normalização**.

Portanto, antes da modelagem, recomenda-se tratar valores ausentes, avaliar outliers e aplicar escalonamento nas variáveis numéricas quando o algoritmo exigir.

## 3.5.4 - Relação entre variáveis numéricas e a variável-alvo
"""

# Comparação de médias das variáveis numéricas por classe do target

num_cols_sem_id = [col for col in df.select_dtypes(include=['int64', 'float64']).columns if col != 'id']

if target in df.columns:
    medias_por_classe = df.groupby(target)[num_cols_sem_id].mean(numeric_only=True).Tdisplay(medias_por_classe)
else:
    print('Variável target não encontrada no DataFrame.')

"""### Interpretação das relações com a variável-alvo

As variáveis que mais se relacionam com a saída são **Academic Pressure**, **Financial Stress**, **Age** e a variável categórica **Have you ever had suicidal thoughts ?**.

A correlação positiva de **Academic Pressure** indica que estudantes com maior pressão acadêmica tendem a apresentar maior ocorrência de depressão. O mesmo comportamento aparece em **Financial Stress**, sugerindo que dificuldades financeiras podem estar associadas ao aumento do risco de depressão.

A variável **Age** apresenta relação negativa com a depressão, indicando maior presença da classe positiva entre estudantes mais jovens. Já **CGPA** apresentou correlação muito baixa, o que sugere que o desempenho acadêmico isolado não é um bom indicador para prever depressão nesse conjunto de dados.

A variável **Have you ever had suicidal thoughts ?** deve ser tratada com cautela. Embora tenha forte relação com a variável-alvo, ela pode representar **vazamento de dados**, pois pensamentos suicidas são um sintoma diretamente associado à depressão. Para uma modelagem mais preventiva, recomenda-se treinar pelo menos um cenário sem essa variável.

## 3.5.5 - Checklist de possíveis problemas da base

- [x] **Valores ausentes:** existem poucos valores ausentes, concentrados em `Financial Stress`.
- [ ] **Linhas duplicadas:** não há duplicatas relevantes considerando o identificador; também foi feita verificação ignorando `id`.
- [x] **Outliers:** há possíveis valores extremos em algumas variáveis, mas devem ser avaliados antes de remoção.
- [x] **Classes desbalanceadas:** há leve desbalanceamento na variável-alvo, mas não é extremo.
- [x] **Colunas irrelevantes ou identificadores:** `id` deve ser removida antes da modelagem; `Profession`, `Work Pressure` e `Job Satisfaction` também foram avaliadas para remoção.
- [x] **Variáveis categóricas que precisam de codificação:** variáveis como `Gender`, `Sleep Duration`, `Dietary Habits`, `Degree` e outras precisam ser transformadas.
- [x] **Variáveis numéricas que precisam de normalização/padronização:** modelos baseados em distância ou otimização matemática devem usar escalonamento.
- [x] **Possível vazamento de dados:** `Have you ever had suicidal thoughts ?` pode causar target leakage.

**Explicação:** a base é adequada para modelagem, mas exige limpeza e preparação antes do treinamento. Os principais cuidados são remover identificadores, tratar a coluna `City`, filtrar registros que não são estudantes, codificar variáveis categóricas, tratar valores ausentes e decidir se a variável de pensamentos suicidas será removida no modelo principal.

# 4 - Preparação para o Modelo

## 4.1 - Feature Engineering inicial

### 4.1.1 - Transformações e Encoding

**VARIÁVEIS BINÁRIAS**

Label Encoding: `object` -> `int64`
"""

print("Antes:")
print(df[[
    "Gender",
    "Have you ever had suicidal thoughts ?",
    "Family History of Mental Illness"
]].head())


df["Gender"] = df["Gender"].map({
    "Male": 0,
    "Female": 1
})

df["Have you ever had suicidal thoughts ?"] = df[
    "Have you ever had suicidal thoughts ?"
].map({
    "No": 0,
    "Yes": 1
})

df["Family History of Mental Illness"] = df[
    "Family History of Mental Illness"
].map({
    "No": 0,
    "Yes": 1
})

print("\nDepois:")
print(df[[
    "Gender",
    "Have you ever had suicidal thoughts ?",
    "Family History of Mental Illness"
]].head())

"""**VARIÁVEIS ORDINAIS**

Ordinal Encoding:
`object` -> `float64`

"""

sleep_map = {
    "Less than 5 hours": 0,
    "5-6 hours": 1,
    "7-8 hours": 2,
    "More than 8 hours": 3,
    "Others": np.nan
}

df["Sleep Duration"] = df["Sleep Duration"].map(sleep_map)

print(df["Sleep Duration"].unique())
print(df["Sleep Duration"].dtype)

diet_map = {
    "Unhealthy": 0,
    "Moderate": 1,
    "Healthy": 2,
    "Others": np.nan
}

df["Dietary Habits"] = df["Dietary Habits"].map(diet_map)

print(df["Dietary Habits"].unique())
print(df["Dietary Habits"].dtype)

"""**VARIÁVEIS NOMINAIS**

One-Hot Encoding
"""

df = pd.get_dummies(df, columns=["Degree"], drop_first=True)
print(df.dtypes)

"""Embora a variável City possua um grande número de categorias, optou-se por mantê-la temporariamente para análises posteriores. Essa decisão permite avaliar sua relevância para a predição da depressão e evitar a exclusão prematura de uma informação que possa contribuir para a identificação de padrões no conjunto de dados. Caso a variável seja mantida nas etapas de modelagem, será necessária a aplicação de técnicas de codificação para variáveis categóricas, como o One-Hot Encoding.

**REMOÇÃO DE VARIÁVEIS**

Considerando que o objetivo do estudo é investigar fatores associados à depressão em estudantes, foram mantidos apenas os registros cuja profissão era classificada como Student. Essa filtragem resultou na remoção de 31 registros (0,11% do conjunto de dados), correspondentes a outras ocupações. Em seguida, a variável Profession foi removida, uma vez que passou a apresentar um único valor para todas as observações restantes, não agregando informação relevante para a análise.
"""

df = df[df["Profession"] == "Student"]
print(df.shape)

df.drop(columns=["Profession"], inplace=True)
print(df.shape)

"""As variáveis Work Pressure e Job Satisfaction foram removidas após a seleção exclusiva de estudantes, pois apresentaram variabilidade praticamente nula (mais de 99% dos registros concentrados no valor zero)."""

df.drop(
    columns=["Work Pressure", "Job Satisfaction"],
    inplace=True
)

print(df.shape)
print(df.columns.tolist())

"""###  4.1.2 - Criação de variáveis derivadas

A criação de variáveis derivadas foi orientada pelos resultados da análise exploratória e do estudo de correlação. As variáveis **Academic Pressure** (correlação de 0,475 com a variável alvo) e **Financial Stress** (correlação de 0,364) apresentaram as associações mais relevantes com a ocorrência de depressão. Além disso, observou-se um aumento consistente da proporção de estudantes com depressão nos níveis mais elevados dessas variáveis. Dessa forma, foram criados os atributos **High_Academic_Pressure** e **High_Financial_Stress**, com o objetivo de representar de forma mais direta estudantes submetidos a altos níveis de pressão acadêmica e estresse financeiro.
"""

# High_Academic_Pressure
df["High_Academic_Pressure"] = (
    df["Academic Pressure"] >= 4
).astype(int)

print(df["High_Academic_Pressure"].value_counts())

# High_Financial_Stress
df["High_Financial_Stress"] = (
    df["Financial Stress"] >= 4
).astype(int)

print(df["High_Financial_Stress"].value_counts())

print(df[[
    "High_Financial_Stress",
    "High_Academic_Pressure"
]].head())

print(df[[
    "High_Financial_Stress",
    "High_Academic_Pressure"
]].dtypes)

"""## 4.2 - Sugestão de pré-processamento

###  4.2.1 - Tratamento definitivo de missing e outliers

Variáveis que apresentam valores ausentes devem ser tratadas antes da modelagem. A estrategia pode variar com o tipo da variável tratada.

#### **Variáveis Numéricas**

Para variáveis numéricas, a abordagem recomendada é a substituição dos valores ausentes pela **mediana**. Essa medida é menos sensível à presença de valores extremos do que a média aritmética, preservando melhor a distribuição original dos dados.

#### **Variáveis Categóricas**

Para variáveis categóricas, recomenda-se a substituição pela **categoria mais frequente (moda)**. Alternativamente, pode-se criar uma nova categoria para representar valores ausentes quando essa ausência puder conter informação relevante para a análise.
"""

# Quantidade e percentual de valores ausentes

missing_count = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Quantidade': missing_count,
    'Percentual (%)': missing_percent
})

missing_df = missing_df[missing_df['Quantidade'] > 0]
missing_df.sort_values('Percentual (%)', ascending=False)

# Preenchimento pela mediana

num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Preenchimento pela moda

cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

"""Em relação aos outliers, a análise exploratória indicou que algumas variáveis apresentam observações extremas. Como esses valores podem representar características reais dos estudantes e não erros de coleta, recomenda-se avaliar seu impacto no desempenho dos modelos antes de optar pela remoção."""

# Identificação de outliers usando IQR

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f'{col}: {len(outliers)} outliers')

import matplotlib.pyplot as plt
import seaborn as sns

for col in numeric_cols:
    plt.figure(figsize=(8,2))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot - {col}')
    plt.show()

"""###  4.2.2 - Normalização/padronização

As variáveis numéricas possuem escalas distintas, podendo influenciar no peso de uma variável em detrimento de outra, o ideal é realizar um tratamento de normalização utilizando técnicas de padronização ou normalização

#### **Padronização (Standardization)**

A padronização transforma os dados de modo que apresentem média igual a 0 e desvio padrão igual a 1. Essa técnica é amplamente utilizada em algoritmos que dependem de distância ou otimização matemática, como Regressão Logística, SVM e KNN.

#### **Normalização (Min-Max Scaling)**

A normalização ajusta os valores para um intervalo fixo, geralmente entre 0 e 1. Essa abordagem preserva a relação proporcional entre os dados e é útil quando se deseja limitar a amplitude das variáveis.
"""

from sklearn.preprocessing import StandardScaler

# Seleciona apenas colunas numéricas
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Cria uma cópia do dataset
df_standardized = df.copy()

# Aplica a padronização
scaler = StandardScaler()
df_standardized[numeric_cols] = scaler.fit_transform(df_standardized[numeric_cols])

df_standardized[numeric_cols].head()

from sklearn.preprocessing import MinMaxScaler

# Seleciona apenas colunas numéricas
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Cria uma cópia do dataset
df_normalized = df.copy()

# Aplica a normalização
scaler = MinMaxScaler()
df_normalized[numeric_cols] = scaler.fit_transform(df_normalized[numeric_cols])

df_normalized[numeric_cols].head()

"""###  4.2.3 - Remoção de colunas irrelevantes

Nem todas as variáveis presentes no conjunto de dados contribuem de forma significativa para a construção de modelos preditivos. Variáveis com baixa variabilidade, informações redundantes, identificadores únicos ou atributos sem relação com a variável alvo podem aumentar a complexidade do modelo sem gerar ganhos de desempenho.

Dessa forma, recomenda-se a análise das variáveis com base em critérios como correlação, importância das features e conhecimento do domínio do problema. A remoção desses atributos pode reduzir a dimensionalidade do conjunto de dados, diminuir o custo computacional e melhorar a capacidade de generalização dos modelos.
"""

# Colunas sem variabilidade

constant_cols = [col for col in df.columns if df[col].nunique() <= 1]

print("Colunas sem variabilidade:")
print(constant_cols)

# Correlação das variáveis numéricas com a variável alvo(depression neste caso)

corr_target = (
    df.select_dtypes(include=['int64', 'float64'])
      .corr()['Depression']
      .sort_values(key=abs, ascending=False)
)

corr_target

# Removendo colunas consideradas irrelevantes

cols_to_drop = [
    'id',      # identificador
    'Name'     # caso exista
]

df_reduced = df.drop(columns=cols_to_drop, errors='ignore')

print(f"Colunas restantes: {df_reduced.shape[1]}")

"""# 5. Conclusões do Estudo

Esta seção sintetiza os principais ponttos obtidos ao longo da análise exploratória e do pipeline de preparação dos dados, fornecendo os dados necessários tanto para o entendimento do problema quanto para as próximas etapas de modelagem preditiva.

## 5.1 - Insights encontrados

A análise exploratória permitiu identificar padrões relevantes associados à ocorrência de depressão entre estudantes.



*   Altos níveis de pressão acadêmica aumentam significativamente a probabilidade de depressão.

Entre todas as variáveis numéricas examinadas, a Pressão Acadêmica apresentou a maior correlação linear positiva com a depressão (0.47). O aumento dos níveis desse indicador está diretamente associado a uma maior proporção de estudantes diagnosticados.

*  O estresse financeiro contribui para o agravamento da saúde mental dos estudantes.

O Estresse Financeiro surge como o segundo preditor numérico mais relevante (correlação de 0.36). Isso valida que as demandas econômicas exercem um peso psicológico significativo sobre a saúde mental do corpo discente.

* Estudantes mais jovens apresentam maior suscetibilidade à depressão.

A Idade apresentou uma correlação negativa (-0.23). Esse comportamento indica que, dentro do intervalo de 18 a 59 anos presente no dataset, os estudantes mais jovens (próximos à média de 25,8 anos) possuem uma tendência estatisticamente maior de relatar quadros depressivos.

*  Notas mais altas ou mais baixas não parecem estar diretamente associadas à ocorrência de depressão.

Ao contrário do senso comum, a média de notas (CGPA) demonstrou uma correlação praticamente nula (0.02) com a depressão. Isso prova que o desempenho acadêmico isolado não é um indicador de bem-estar ou sofrimento psíquico neste grupo.

*  Pensamentos suicidas podem atuar como um forte indicador de quadros depressivos.

A variável categórica Have you ever had suicidal thoughts ? possui uma relação fortíssima com o público diagnosticado, operando quase como um indicador direto do estado avançado da condição.

## 5.2 - Hipóteses geradas

Hipótese 1 : A maior incidência de depressão em estudantes mais jovens pode estar associada às dificuldades de transição para o ensino superior, falta de rede de apoio local nas novas cidades e imaturidade no manejo de crises.

Hipótese 2 : Existe um efeito crítico onde níveis de Pressão Acadêmica e Estresse Financeiro iguais ou superiores a 4 acionam uma probabilidade exponencialmente maior de desenvolvimento da depressão. As variáveis derivadas *High_Academic_Pressure* e *High_Financial_Stress* criadas na engenharia de atributos devem se provar os preditores mais fortes nos modelos de árvore.

Hipótese 3 : A duração do sono inferior a 5 horas não é apenas um sintoma, mas um fator mediador que amplifica o impacto da Pressão Acadêmica no desenvolvimento de transtornos psicológicos.

## 5.3 - Limitações do Dataset

Apesar da boa qualidade geral dos dados, algumas limitações devem ser consideradas durante a interpretação dos resultados e o desenvolvimento dos modelos.

* **Vazamento Potencial de Conceito (Target Leakage):** A variável *Have you ever had suicidal thoughts ?* é clinicamente um sintoma grave do próprio quadro depressivo. Mantê-la no modelo pode inflar artificialmente a acurácia do algoritmo, gerando um modelo que não previne a depressão, mas apenas identifica quando ela já está em estágio crítico.

* **Presença de Ruído na Coleta de Dados:** A coluna City apresentou sérias inconsistências de inputting, como a mistura de nomes próprios como "Saanvi", siglas de cursos como "M.Tech" e erros de digitação como "Khaziabad". Gerando a necessidade de uma limpeza manual.

* **Falta de Contexto Socioeconômico Detalhado:** Embora o dataset avalie o "Estresse Financeiro" em uma escala ordinal de 1 a 5, não há dados objetivos sobre renda familiar, recebimento de bolsas de estudo ou se o estudante precisa conciliar o curso com um emprego formal.

* **Viés de Amostragem Original:** O dataset continha registros de profissões variadas (como Chef, Arquiteto, etc.) infiltrados em um conjunto nominalmente voltado para estudantes. Embora tenham sido filtrados e removidos (31 registros), isso aponta para possíveis fragilidades no controle de qualidade da coleta original no Kaggle.

Além disso, algumas variáveis são baseadas em autorrelato dos participantes, o que pode introduzir vieses de percepção, memória ou desejabilidade social, afetando a precisão das respostas fornecidas.

Por fim, os dados foram obtidos a partir de uma única fonte pública e podem não representar adequadamente todos os perfis de estudantes, limitando a capacidade de generalização dos resultados para outras populações, regiões geográficas ou contextos educacionais.

# 6 - Planejamento da Modelagem

## 6.1 - Resposta do grupo: planejamento inicial da modelagem

1. **Qual é a variável-alvo?**  
A variável-alvo é **Depression**.

2. **O problema é classificação ou regressão?**  
O problema é de **classificação binária supervisionada**, pois o modelo deverá prever se o estudante pertence à classe `0` ou `1`.

3. **Quais colunas serão usadas como entrada?**  
Inicialmente, serão consideradas variáveis relacionadas ao perfil do estudante, pressão acadêmica, satisfação com os estudos, carga de estudo/trabalho, sono, hábitos alimentares, estresse financeiro, histórico familiar e curso/grau. Exemplos: `Age`, `Gender`, `Academic Pressure`, `CGPA`, `Study Satisfaction`, `Sleep Duration`, `Dietary Habits`, `Degree`, `Work/Study Hours`, `Financial Stress` e `Family History of Mental Illness`.

4. **Quais colunas podem ser removidas?**  
Devem ser removidas ou avaliadas:

- `id`, por ser apenas identificador;
- `Profession`, após filtrar apenas estudantes;
- `Work Pressure` e `Job Satisfaction`, por apresentarem baixa variabilidade no contexto de estudantes;
- `City`, caso a limpeza/codificação não gere ganho relevante;
- `Have you ever had suicidal thoughts ?`, no cenário principal, por possível vazamento de dados.

5. **Quais tratamentos serão necessários?**  
Antes do treinamento, será necessário:

- tratar valores ausentes, especialmente em `Financial Stress`;
- remover ou filtrar registros inconsistentes;
- codificar variáveis categóricas;
- avaliar outliers;
- aplicar normalização ou padronização quando o algoritmo exigir;
- dividir os dados em treino e teste com estratificação;
- testar um cenário com e outro sem a variável de possível vazamento.

6. **Quais algoritmos o grupo pretende testar?**  
Como o problema é de classificação, os modelos iniciais sugeridos são:

- Regressão Logística;
- KNN;
- Árvore de Decisão;
- Random Forest;
- Naive Bayes;
- SVM.

A avaliação deverá considerar **matriz de confusão**, **acurácia**, **precision**, **recall**, **F1-score** e, se possível, **ROC-AUC**. Como o tema envolve depressão, o recall da classe positiva deve receber atenção, pois falsos negativos podem ser mais críticos.

# 7 - Mini-relatório Final da Exploração

O objetivo deste projeto é analisar dados relacionados à depressão em estudantes e construir uma base preparada para o desenvolvimento de modelos de Machine Learning capazes de prever a ocorrência de depressão a partir de características acadêmicas, pessoais e comportamentais.

Cada linha do dataset representa um estudante, contendo informações como idade, gênero, cidade, curso/grau, pressão acadêmica, satisfação com os estudos, duração do sono, hábitos alimentares, horas de estudo/trabalho, estresse financeiro, histórico familiar de doença mental e a variável-alvo `Depression`.

A variável-alvo é **Depression**, que indica se o estudante apresenta ou não depressão. Como essa variável possui duas classes, o problema é de **classificação binária**.

Durante a análise exploratória, as variáveis que pareceram mais importantes foram **Academic Pressure**, **Financial Stress**, **Age** e **Have you ever had suicidal thoughts ?**. A pressão acadêmica e o estresse financeiro apresentaram relação positiva com a depressão, indicando que níveis mais altos desses fatores estão associados a maior presença da classe positiva. A idade apresentou relação negativa, sugerindo maior incidência de depressão em estudantes mais jovens. Já a variável sobre pensamentos suicidas mostrou forte associação com a saída, mas deve ser analisada com cuidado por representar possível vazamento de dados.

A base apresentou poucos valores ausentes, concentrados principalmente em `Financial Stress`. Também foram identificadas inconsistências na coluna `City`, presença de registros com profissões diferentes de estudante, variáveis com baixa variabilidade e colunas que precisam de codificação antes da modelagem. Além disso, a coluna `id` deve ser removida por funcionar apenas como identificador.

Antes do treinamento dos modelos, serão aplicados tratamentos como limpeza de registros inconsistentes, preenchimento de valores ausentes, codificação de variáveis categóricas, remoção de colunas irrelevantes, possível exclusão da variável de vazamento e normalização/padronização das variáveis numéricas quando necessário.

Inicialmente, o grupo pretende testar modelos de classificação como Regressão Logística, KNN, Árvore de Decisão, Random Forest, Naive Bayes e SVM. Os modelos serão comparados usando métricas adequadas para classificação, principalmente matriz de confusão, acurácia, precision, recall e F1-score.
"""